### ISSUE TITLE
Add JSON endpoints

### ISSUE THREAD

**Issue by pmallory** [pmallory/Catalog#1]
Endpoints for the /catalog, /catalog/category and /catalog/category/item

**Comment by eduardomed** [comment]
@pmallory @walesmd JSON endpoints have been added as: 

/catalog/json
/catalog/categories/json
/catalog/categories/items/json

There might be a more efficient way to implement the endpoints. I took Lorenzo's approach, basically outlined here: http://stackoverflow.com/questions/7102754/jsonify-a-sqlalchemy-result-set-in-flask

Can one of you verify and close this ticket?

**Comment by walesmd** [comment]
Getting an error on the first endpoint. If I go to `http://localhost:8000/catalog/json` I get a 404. If I go to `http://localhost:8000/catalog/catalog/json` I get the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/Catalog/application.py", line 48, in item_page
    item_select = db_session.query(Item).filter_by(title = item_name).one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2401, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
```

**Comment by eduardomed** [comment]
We just did an update, the correct paths should be: 

/catalog.json
/catalog/categories.json
/catalog/categories/items.json

Can you pull and check again?
